description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Nunito Sans"
      fonts: 
        - 
          asset: "fonts/NunitoSans-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/NunitoSans-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/NunitoSans-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Aguafina Script"
      fonts: 
        - 
          asset: "fonts/AguafinaScript-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Actor"
      fonts: 
        - 
          asset: "fonts/Actor-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Acme"
      fonts: 
        - 
          asset: "fonts/Acme-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Advent Pro"
      fonts: 
        - 
          asset: "fonts/AdventPro-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/AdventPro-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Work Sans"
      fonts: 
        - 
          asset: "fonts/WorkSans-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
